name: ci

on:
  pull_request:
  push:
    branches:
      - master
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang env
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false # conflict with golangci-lint cache
      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang env
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Build
        run: go build
      - name: Unit Test
        run: go test -v
